### ISSUE TITLE
Find gliph3 difference supporting dataset for vignette

### ISSUE THREAD

**Issue by kaozkai** [snaketron/ClustIRR#20]
[Single-cell RNA sequencing coupled to TCR
profiling of large granular lymphocyte leukemia
T cells](https://www.nature.com/articles/s41467-022-29175-x)

Data with HLA included

**Comment by snaketron** [comment]
To be clear, this is what I had in mind:
1. we need a dataset based on which we can test clustIRR (realize if any functionality/interfaces are currently missing, fix potential bugs) 
2. we can use part of the results to populate vignette
3. if you like the dataset you can analyze it during your thesis
4. Other interesting datasets might be available out there -> we need to look for them
