### ISSUE TITLE
Add get_igraph() function

### ISSUE THREAD

**Issue by kaozkai** [snaketron/ClustIRR#24]
- [x] replace or complement get_edges() function with function to receive igraph compatible data object

**Comment by snaketron** [comment]
Some things to consider when building the graphing module @kaozkai and @snaketron:

We have to really think how to structure the resulting graph:
* what is the interpretation of a vertex: a CDR3 sequence or a cell? if v=1 or v=2, then each vertex is a CDR3 sequence; else, each vertex is a cell
* imagine the example from the vignette in which you introduce clonal expansion, i.e. we have 15 cells with the same CDR3 sequences. If we represent each cell as a vertex, then we have a completely connected subgraph of n=15, and the number of edges grows exponentially with n. Maybe we need to think about a special way of representing clonal expansions in the graph.
* edges can represent a) enriched motifs or b) global pairs from CDR3b or CDR3a. Do we show 1 edge in which we somehow encode this information such that it may be retrieved later on, or do we draw multiple edges or a weighted edge?
* maybe there are other points I have missed here ...

We can talk about these points on Thursday.
