### ISSUE TITLE
NAMESPACE file

### ISSUE THREAD

**Issue by snaketron** [snaketron/ClustIRR#26]
@kaozkai  Which functions should be exported by ClustIRR?

Currently, we export:

export(cluster_irr)
export(get_graph)
export(get_edges)
export(plot_graph)

I would guess we need cluster_irr, get_graph and plot_graph. 
Do we really need to have get_edges visible to the user?

**Comment by kaozkai** [comment]
hey @snaketron , yes, I guess we could even reduce it further to only cluster_irr() and plot_graph(), if we want to.
Noticed yesterday that you can access all nodes and edges from a saved visNetwork object, 
so I think there is no benefit in exporting get_edges(), and even get_graph() could be left as internal function and only added if asked for.

**Comment by snaketron** [comment]
Great! From the user's point of view this sounds beneficial -> simple to use
