### ISSUE TITLE
BiocCheck Status

### ISSUE THREAD

**Issue by kaozkai** [snaketron/ClustIRR#7]
_Errors_
- [x] package size: Package tarball exceeds the Bioconductor size requirement. is: 6.2mb should be: <5mb (added hs_CD4_ref.RData to build ignore for now)
- [x] valid maintainer: Remove Maintainer field. Use Authors@R [cre] designation.
- [x] vignette directory: No 'vignettes' directory. (created dummy vignette)
- [x] man page documentation: At least 80% of man pages documenting exported objects must have runnable examples. (added minimal example, to be expanded with meaningful one)

_Warnings_
- [x] DESCRIPTION/NAMESPACE consistency: Import methods in NAMESPACE as well as DESCRIPTION.
- [x] coding practice: Avoid T/F variables; If logical, use TRUE/FALSE

_Notes_
- [x] Description: field: The Description field in the DESCRIPTION is made up by less than 3 sentences. Please consider expanding this field, and structure it as a full paragraph
- [x] coding practice: 
  - [x] Avoid 1:...; use seq_len() or seq_along()
  - [x] Avoid the use of 'paste' in condition signals
- [ ] function lengths: The recommended function length is 50 lines or less. There are 5 functions greater than 50 lines.
- [x] unit tests: Consider adding unit tests. We strongly encourage them. See https://contributions.bioconductor.org/tests.html
- [ ] formatting of DESCRIPTION, NAMESPACE, man pages, R source, and vignette source:
  - [ ] Consider shorter lines; 4 lines (0%) are > 80 characters long. (roxgen auto-created, man/gliph.Rd)
  - [ ] Consider multiples of 4 spaces for line indents; 102 lines (5%) are not. See https://contributions.bioconductor.org/r-code.html / See styler package: https://cran.r-project.org/package=styler as described in the BiocCheck vignette.
- [ ] bioc-devel mailing list subscription: Cannot determine whether maintainer is subscribed to the Bioc-Devel mailing list (requires admin credentials). Subscribe here: https://stat.ethz.ch/mailman/listinfo/bioc-devel

_Registration_
- [ ] support site registration: Unable to connect to support site: Peer certificate cannot be authenticated with given CA certificates: [support.bioconductor.org] SSL certificate problem: certificate has expired

**Comment by snaketron** [comment]
> package size: Package tarball exceeds the Bioconductor size requirement. is: 6.2mb should be: <5mb (added hs_CD4_ref.RData to build ignore for now)

The unit of interest in gliph v3 is a T-cell (nodes in the graph are T-cells)
In gliph v1-2 this was not the case, i.e. in these version the unit of interest was non-redundant CDR3 sequence.

Hence, for v3 we either 1) need new reference databases (e.g. from single cell experiments of naive T cell receptor repertoires) or 2) we proceed without a reference and we ask the user to provide one. We have to think about this.

**Comment by snaketron** [comment]
We have the bulk of these TODOs covered. The rest can be fixed during package submission.

If you agree with this please close this issue.
